/*
   Generated by EX4 TO MQ4 decompile Service 
   Website: http://www.ex4Tomq4.net 
   E-mail : info@ex4Tomq4.net 
*/

#property indicator_separate_window
#property indicator_minimum 0.0
#property indicator_maximum 0.1

extern string Version = "19";
extern string AlertName = "Envy Margin In Use Alert";
extern bool ResetMaxMarginUsed = FALSE;
extern bool ReduceMarginBalancebyBonus = FALSE;
extern bool AlertTest = FALSE;
extern double Deposits = 95000.0;
extern double Bonuses = 32434.07;
extern int Alerts = 0;
extern int BA1 = 12;
extern bool BA1Trig = FALSE;
extern int BA2 = 15;
extern bool BA2Trig = FALSE;
extern double MA1 = 50.0;
extern bool MA1Trig = FALSE;
extern double MA2 = 60.0;
extern bool MA2Trig = FALSE;
extern double MA3 = 70.0;
extern bool MA3Trig = FALSE;
extern color HeaderColor = Gold;
extern color PosColor = Lime;
extern color NegColor = Red;
extern color NulColor = Silver;
extern int FontSize = 10;
extern string font = "Arial Bold";
string gs_204 = " ";

int init() {
   IndicatorShortName(gs_204);
   IndicatorDigits(0);
   SetIndexEmptyValue(0, 0.0);
   ObjectsRedraw();
   return (0);
}

int deinit() {
   int li_0 = WindowFind(gs_204);
   if (li_0 > 0) ObjectsDeleteAll(li_0);
   ObjectsRedraw();
   return (0);
}

double f0_2(int ai_0) {
   double ld_4 = 0.0;
   double ld_ret_12 = 0.0;
   for (int pos_20 = OrdersTotal() - 1; pos_20 >= 0; pos_20--) {
      if (OrderSelect(pos_20, SELECT_BY_POS, MODE_TRADES)) {
         ld_4 = OrderProfit() + OrderCommission() + OrderSwap();
         if (ai_0 == 1)
            if (ld_4 >= 0.0) ld_ret_12 += ld_4;
         if (ai_0 == 2)
            if (ld_4 < 0.0) ld_ret_12 += ld_4;
      }
   }
   return (ld_ret_12);
}

double f0_1() {
   double ld_ret_0 = 0.0;
   for (int pos_8 = OrdersTotal() - 1; pos_8 >= 0; pos_8--)
      if (OrderSelect(pos_8, SELECT_BY_POS, MODE_TRADES)) ld_ret_0 += OrderLots();
   if (ld_ret_0 == 0.0) ld_ret_0 = 0.000001;
   return (ld_ret_0);
}

int f0_0(double ad_0) {
   Alerts++;
   if (Alerts == 1) {
      SendMail(AlertName, "Envy Margin in use >= " + DoubleToStr(ad_0, 1) + "%");
      Print("Envy Margin in use >= " + DoubleToStr(ad_0, 1) + "%");
      Alert("Envy Margin in use >= " + DoubleToStr(ad_0, 1) + "%");
   } else
      if (Alerts <= 100) PlaySound("alert2.wav");
   if (Alerts == 100) return (1);
   return (0);
}

int start() {
   string lsa_32[15][17];
   string lsa_36[15];
   string lsa_40[15];
   int lia_44[15];
   ObjectsRedraw();
   string symbol_0 = "";
   string name_8 = "";
   string ls_unused_16 = "";
   string text_24 = "";
   lsa_36[0] = " 01 L EurUsd";
   lsa_36[1] = " 02 L GbpUsd";
   lsa_36[2] = " 03 L EurJpy";
   lsa_36[3] = " 04 L EurGbp";
   lsa_36[4] = " 05 L UsdCad";
   lsa_36[5] = " 06 L AudUsd";
   lsa_36[6] = " 07 L NzdUsd";
   lsa_36[7] = " 08 L UsdJpy";
   lsa_36[8] = " 09 L AudNzd";
   lsa_36[9] = " -----------";
   lsa_36[10] = " 11 S EurUsd";
   lsa_36[11] = " 12 S GbpUsd";
   lsa_36[12] = " 13 S EurJpy";
   lsa_36[13] = " 14 S UsdCad";
   lsa_36[14] = " 15 S UsdJpy";
   lsa_40[0] = "M# C  Sym ";
   lsa_40[1] = "BLot";
   lsa_40[2] = " # ";
   lsa_40[3] = "  B-TP";
   lsa_40[4] = "   B-PL";
   lsa_40[5] = ">  ";
   lsa_40[6] = " A+B/2 ";
   lsa_40[7] = "<  ";
   lsa_40[8] = "  S-PL";
   lsa_40[9] = " S-TP ";
   lsa_40[10] = " # ";
   lsa_40[11] = "SLot";
   lsa_40[12] = "  Swap";
   lsa_40[13] = "<> ";
   lsa_40[14] = "Sv";
   int li_48 = 0;
   int li_52 = 0;
   int li_56 = 0;
   int li_60 = 0;
   int li_64 = 0;
   int li_unused_68 = 0;
   int li_unused_72 = 0;
   int cmd_76 = -1;
   int li_unused_80 = 15;
   int y_84 = 8;
   int li_88 = WindowFind(gs_204);
   int index_92 = 0;
   int pos_96 = 0;
   int li_100 = 0;
   bool digits_104 = FALSE;
   double ld_108 = 0.0;
   double ld_unused_116 = 0.0;
   double str2dbl_124 = 0.0;
   double str2dbl_132 = 0.0;
   double ld_140 = 0.0;
   double ld_148 = 0.0;
   double ld_156 = 0.0;
   double order_lots_164 = 0.0;
   double order_open_price_172 = 0.0;
   double ld_180 = 0.0;
   double ld_188 = 0.0;
   color color_196 = CLR_NONE;
   double ld_200 = GlobalVariableGet("MaxMarginUsed1");
   if (ResetMaxMarginUsed) {
      GlobalVariableSet("MaxMarginUsed1", 0);
      ResetMaxMarginUsed = FALSE;
   }
   if (li_88 > 0) {
      ObjectsDeleteAll(li_88);
      for (pos_96 = 0; pos_96 < 15; pos_96++) {
         if (pos_96 == 0) lia_44[pos_96] = 12;
         else lia_44[pos_96] = lia_44[pos_96 - 1] + FontSize * StringLen(lsa_40[pos_96 - 1]) - FontSize / 2.0;
      }
      for (pos_96 = 0; pos_96 < 15; pos_96++) {
         lsa_32[pos_96][0] = "--------------";
         lsa_32[pos_96][1] = "-----";
         lsa_32[pos_96][2] = "-";
         lsa_32[pos_96][4] = "-----";
         lsa_32[pos_96][3] = "-----";
         lsa_32[pos_96][5] = "-";
         lsa_32[pos_96][6] = "-----";
         lsa_32[pos_96][7] = "-";
         lsa_32[pos_96][9] = "-----";
         lsa_32[pos_96][8] = "-----";
         lsa_32[pos_96][10] = "-";
         lsa_32[pos_96][11] = " -----";
         lsa_32[pos_96][12] = "---";
         lsa_32[pos_96][13] = "-";
         lsa_32[pos_96][14] = "-";
         lsa_32[pos_96][15] = "-";
         lsa_32[pos_96][16] = "-";
      }
      for (pos_96 = OrdersTotal() - 1; pos_96 >= 0; pos_96--) {
         if (OrderSelect(pos_96, SELECT_BY_POS, MODE_TRADES)) {
            if (OrderType() != OP_SELL && OrderType() != OP_BUY) continue;
            symbol_0 = OrderSymbol();
            cmd_76 = OrderType();
            order_lots_164 = OrderLots();
            order_open_price_172 = OrderOpenPrice();
            digits_104 = MarketInfo(symbol_0, MODE_DIGITS);
            ld_188 = OrderSwap();
            ld_180 = OrderProfit() + OrderCommission() + ld_188;
            li_100 = OrderMagicNumber() - 1;
            if (li_100 >= 15 || li_100 < 0) continue;
            lsa_32[li_100][0] = symbol_0;
            if (cmd_76 == OP_BUY) {
               if (OrderStopLoss() == 0.0 || OrderTakeProfit() == 0.0) lsa_32[li_100][15] = "0SL";
               lsa_32[li_100][1] = DoubleToStr(StrToDouble(lsa_32[li_100][1]) + order_lots_164, 2);
               lsa_32[li_100][2] = DoubleToStr(StrToInteger(lsa_32[li_100][2]) + 1, 0);
               lsa_32[li_100][3] = DoubleToStr(OrderTakeProfit(), digits_104);
               lsa_32[li_100][4] = DoubleToStr(StrToDouble(lsa_32[li_100][4]) + ld_180, 2);
               if (MarketInfo(symbol_0, MODE_DIGITS) == 5.0) lsa_32[li_100][5] = DoubleToStr(100000.0 * (OrderTakeProfit() - MarketInfo(symbol_0, MODE_BID)), 0);
               else {
                  if (MarketInfo(symbol_0, MODE_DIGITS) == 4.0) lsa_32[li_100][5] = DoubleToStr(10000.0 * (OrderTakeProfit() - MarketInfo(symbol_0, MODE_BID)), 0);
                  else {
                     if (MarketInfo(symbol_0, MODE_DIGITS) == 3.0) lsa_32[li_100][5] = DoubleToStr(1000.0 * (OrderTakeProfit() - MarketInfo(symbol_0, MODE_BID)), 0);
                     else
                        if (MarketInfo(symbol_0, MODE_DIGITS) == 2.0) lsa_32[li_100][5] = DoubleToStr(100.0 * (OrderTakeProfit() - MarketInfo(symbol_0, MODE_BID)), 0);
                  }
               }
            }
            if (cmd_76 == OP_SELL) {
               if (OrderStopLoss() == 0.0 || OrderTakeProfit() == 0.0) lsa_32[li_100][16] = "0SL";
               lsa_32[li_100][8] = DoubleToStr(StrToDouble(lsa_32[li_100][8]) + ld_180, 2);
               lsa_32[li_100][11] = DoubleToStr(StrToDouble(lsa_32[li_100][11]) + order_lots_164, 2);
               lsa_32[li_100][10] = DoubleToStr(StrToInteger(lsa_32[li_100][10]) + 1, 0);
               lsa_32[li_100][9] = DoubleToStr(OrderTakeProfit(), digits_104);
               if (MarketInfo(symbol_0, MODE_DIGITS) == 5.0) lsa_32[li_100][7] = DoubleToStr(100000.0 * (MarketInfo(symbol_0, MODE_ASK) - OrderTakeProfit()), 0);
               else {
                  if (MarketInfo(symbol_0, MODE_DIGITS) == 4.0) lsa_32[li_100][7] = DoubleToStr(10000.0 * (MarketInfo(symbol_0, MODE_ASK) - OrderTakeProfit()), 0);
                  else {
                     if (MarketInfo(symbol_0, MODE_DIGITS) == 3.0) lsa_32[li_100][7] = DoubleToStr(1000.0 * (MarketInfo(symbol_0, MODE_ASK) - OrderTakeProfit()), 0);
                     else
                        if (MarketInfo(symbol_0, MODE_DIGITS) == 2.0) lsa_32[li_100][5] = DoubleToStr(100.0 * (OrderTakeProfit() - MarketInfo(symbol_0, MODE_BID)), 0);
                  }
               }
            }
            lsa_32[li_100][6] = DoubleToStr((MarketInfo(symbol_0, MODE_ASK) + MarketInfo(symbol_0, MODE_BID)) / 2.0, digits_104);
            lsa_32[li_100][12] = DoubleToStr(StrToDouble(lsa_32[li_100][12]) + ld_188, 2);
            if (MarketInfo(symbol_0, MODE_DIGITS) == 4.0) lsa_32[li_100][13] = DoubleToStr(MarketInfo(symbol_0, MODE_SPREAD), 0);
            else lsa_32[li_100][13] = DoubleToStr(MarketInfo(symbol_0, MODE_SPREAD) / 1.0, 0);
            lsa_32[li_100][14] = DoubleToStr(MarketInfo(symbol_0, MODE_STOPLEVEL), 0);
         }
      }
      color_196 = HeaderColor;
      name_8 = "ShowOrders";
      if (ObjectCreate(name_8, OBJ_LABEL, li_88, 0, 0)) {
         ObjectSet(name_8, OBJPROP_XDISTANCE, 15);
         ObjectSet(name_8, OBJPROP_YDISTANCE, y_84);
         ObjectSetText(name_8, "  EnvyDeskTop" + Version + "       " + TimeToStr(TimeCurrent(), TIME_DATE|TIME_SECONDS) + "       P/L $" + DoubleToStr(AccountBalance() - Deposits,
            2), 14, font, DeepPink);
      }
      y_84 += 28;
      for (index_92 = 0; index_92 < 15; index_92++) {
         name_8 = "ShowOrders_" + index_92;
         if (ObjectCreate(name_8, OBJ_LABEL, li_88, 0, 0)) {
            ObjectSet(name_8, OBJPROP_XDISTANCE, lia_44[index_92]);
            ObjectSet(name_8, OBJPROP_YDISTANCE, y_84);
            ObjectSetText(name_8, lsa_40[index_92], FontSize, font, color_196);
         }
      }
      y_84 += FontSize + 0.7 * FontSize;
      for (pos_96 = 0; pos_96 < 15; pos_96++) {
         for (index_92 = 0; index_92 < 15; index_92++) {
            symbol_0 = lsa_32[pos_96][0];
            name_8 = "ShowOrders_" + symbol_0 + " " + pos_96 + " " + index_92;
            if (ObjectCreate(name_8, OBJ_LABEL, li_88, 0, 0)) {
               color_196 = NulColor;
               if (StrToDouble(lsa_32[pos_96][index_92]) > 0.0) color_196 = PosColor;
               else color_196 = NegColor;
               if (StrToDouble(lsa_32[pos_96][index_92]) == 0.0) color_196 = NulColor;
               if (index_92 == 5 || index_92 == 7 || index_92 == 0 || index_92 == 2 || index_92 == 10 || index_92 == 3 || index_92 == 9 || index_92 == 6 || index_92 == 13 || index_92 == 14) color_196 = NulColor;
               ld_140 = (StrToDouble(lsa_32[pos_96][3]) + StrToDouble(lsa_32[pos_96][9])) / 2.0;
               ld_148 = StrToDouble(lsa_32[pos_96][3]) - ld_140;
               if (ld_148 == 0.0) ld_148 = 0.000001;
               str2dbl_132 = StrToDouble(lsa_32[pos_96][6]);
               str2dbl_124 = str2dbl_132;
               li_48 = 180;
               li_52 = 254 - li_48;
               li_56 = 180;
               li_60 = 254 - li_56;
               if (index_92 == 1 || index_92 == 2 || index_92 == 3 || index_92 == 5) {
                  if (pos_96 != 9) {
                     if (lsa_32[pos_96][15] == "0SL") color_196 = Red;
                     else {
                        if (str2dbl_124 > ld_140 || StrToDouble(lsa_32[pos_96][9]) == 0.0) {
                           li_64 = li_60 * ((ld_140 - str2dbl_124) / ld_148);
                           color_196 = 256.0 * MathMax(li_56, li_64 + li_56);
                        } else {
                           if (str2dbl_124 < ld_140) {
                              li_64 = li_52 * ((str2dbl_124 - ld_140) / ld_148);
                              color_196 = C'0x64,0x64,0x64';
                           } else color_196 = NulColor;
                        }
                     }
                  }
               }
               if (index_92 == 11 || index_92 == 10 || index_92 == 9 || index_92 == 7) {
                  if (pos_96 != 9) {
                     if (lsa_32[pos_96][16] == "0SL") color_196 = Red;
                     else {
                        if (str2dbl_132 < ld_140 || StrToDouble(lsa_32[pos_96][3]) == 0.0) {
                           li_64 = li_60 * ((ld_140 - str2dbl_132) / ld_148);
                           color_196 = 256.0 * MathMax(li_56, li_64 + li_56);
                        } else {
                           if (str2dbl_132 > ld_140) {
                              li_64 = li_52 * ((str2dbl_132 - ld_140) / ld_148);
                              color_196 = C'0x64,0x64,0x64';
                           } else color_196 = NulColor;
                        }
                     }
                  }
               }
               if (StringSubstr(lsa_32[pos_96][index_92], 0, 2) == "--") color_196 = NulColor;
               if (index_92 == 6 || index_92 == 13 || index_92 == 14) color_196 = LightBlue;
               if (pos_96 == 9 || index_92 == 0) color_196 = White;
               if (index_92 == 3 || index_92 == 6 || index_92 == 9) ObjectSet(name_8, OBJPROP_XDISTANCE, lia_44[index_92] + 0.8 * FontSize * (7 - StringLen(lsa_32[pos_96][index_92])));
               else {
                  if (index_92 == 12 || index_92 == 4 || index_92 == 8) ObjectSet(name_8, OBJPROP_XDISTANCE, lia_44[index_92] + 0.7 * FontSize * (7 - StringLen(lsa_32[pos_96][index_92])));
                  else {
                     if (index_92 == 2 || index_92 == 10 || index_92 == 5 || index_92 == 7 || index_92 == 13) ObjectSet(name_8, OBJPROP_XDISTANCE, lia_44[index_92] + 0.7 * FontSize * (2 - StringLen(lsa_32[pos_96][index_92])));
                     else ObjectSet(name_8, OBJPROP_XDISTANCE, lia_44[index_92]);
                  }
               }
               ObjectSet(name_8, OBJPROP_YDISTANCE, y_84);
               ld_108 = 0;
               if (pos_96 != 9)
                  if (ld_140 != 0.0) ld_108 = MathAbs(100.0 * (2.0 * ld_148 / ld_140));
               if (ld_108 >= 100.0) {
                  ld_108 = 0;
                  ld_unused_116 = 1;
               } else {
                  if (ld_108 >= 10.0) ld_unused_116 = 0;
                  else ld_unused_116 = 1;
               }
               if (index_92 == 0) {
                  ObjectSetText(name_8, lsa_36[pos_96], FontSize, font, LightBlue);
                  continue;
               }
               ObjectSetText(name_8, lsa_32[pos_96][index_92], FontSize, font, color_196);
            }
         }
         y_84 += FontSize + 0.6 * FontSize;
      }
      color_196 = HeaderColor;
      y_84 += FontSize + 0.0 * FontSize;
      name_8 = "ShowOrders_a1";
      if (ObjectCreate(name_8, OBJ_LABEL, li_88, 0, 0)) {
         ObjectSet(name_8, OBJPROP_XDISTANCE, 12);
         ObjectSet(name_8, OBJPROP_YDISTANCE, y_84);
         ObjectSetText(name_8, "$" + DoubleToStr(-AccountMargin(), 0) + " to Open " + OrdersTotal() + " Orders, " + DoubleToStr(f0_1(), 2) + " Lots, $" + DoubleToStr(AccountMargin() / (100.0 * f0_1()),
            2) + " / 0.01 Lot", FontSize, font, color_196);
      }
      name_8 = "ShowOrders_a1a";
      if (ObjectCreate(name_8, OBJ_LABEL, li_88, 0, 0)) {
         ObjectSet(name_8, OBJPROP_XDISTANCE, 412);
         ObjectSet(name_8, OBJPROP_YDISTANCE, y_84);
         ObjectSetText(name_8, "Leverage " + DoubleToStr(AccountLeverage(), 0), FontSize, font, color_196);
      }
      y_84 += FontSize + 0.7 * FontSize;
      text_24 = "$" + DoubleToStr(AccountProfit(), 0) + " Floating (Profit $" + DoubleToStr(f0_2(1), 0) + ", Loss $" + DoubleToStr(f0_2(2), 0) + "), Bonus $" + DoubleToStr(Bonuses,
         0);
      name_8 = "ShowOrders_a2";
      if (ObjectCreate(name_8, OBJ_LABEL, li_88, 0, 0)) {
         ObjectSet(name_8, OBJPROP_XDISTANCE, 12);
         ObjectSet(name_8, OBJPROP_YDISTANCE, y_84);
         ObjectSetText(name_8, text_24, FontSize, font, color_196);
      }
      name_8 = "ShowOrders_a2a";
      if (ObjectCreate(name_8, OBJ_LABEL, li_88, 0, 0)) {
         ObjectSet(name_8, OBJPROP_XDISTANCE, 412);
         ObjectSet(name_8, OBJPROP_YDISTANCE, y_84);
         ObjectSetText(name_8, "StopOut " + DoubleToStr(AccountStopoutLevel(), 0) + "%, Mode " + DoubleToStr(AccountStopoutMode(), 0), FontSize, font, color_196);
      }
      if (ReduceMarginBalancebyBonus) ld_156 = 100.0 * MathAbs(((-AccountMargin()) + AccountProfit()) / (AccountBalance() - Bonuses));
      else ld_156 = 100.0 * MathAbs(((-AccountMargin()) + AccountProfit()) / AccountBalance());
      if (ld_156 > ld_200) {
         GlobalVariableSet("MaxMarginUsed1", ld_156);
         ld_200 = ld_156;
      }
      if (ld_156 >= MA1 || AlertTest)
         if (!MA1Trig) MA1Trig = f0_0(MA1);
      if (ld_156 >= MA2 || AlertTest)
         if (!MA2Trig) MA2Trig = f0_0(MA2);
      if (ld_156 >= MA3 || AlertTest)
         if (!MA3Trig) MA3Trig = f0_0(MA3);
      AlertTest = FALSE;
      y_84 += FontSize + 0.7 * FontSize;
      if (ReduceMarginBalancebyBonus) {
         text_24 = "$" + DoubleToStr((-AccountMargin()) + AccountProfit(), 0) + " / " + DoubleToStr(ld_156, 1) + "%, In Use, " + DoubleToStr(ld_200, 1) + "% Max, Free $" + DoubleToStr(AccountFreeMargin() - Bonuses,
            0) + ", Cover " + DoubleToStr(100.0 * ((AccountEquity() - Bonuses) / (AccountMargin() + 1.0)), 0) + "%";
      } else {
         text_24 = "$" + DoubleToStr((-AccountMargin()) + AccountProfit(), 0) + " / " + DoubleToStr(ld_156, 1) + "%, In Use, " + DoubleToStr(ld_200, 1) + "% Max, Free $" + DoubleToStr(AccountFreeMargin(),
            0) + ", Level " + DoubleToStr(100.0 * (AccountEquity() / (AccountMargin() + 1.0)), 0) + "%";
      }
      name_8 = "ShowOrders_a3";
      if (ObjectCreate(name_8, OBJ_LABEL, li_88, 0, 0)) {
         ObjectSet(name_8, OBJPROP_XDISTANCE, 12);
         ObjectSet(name_8, OBJPROP_YDISTANCE, y_84);
         ObjectSetText(name_8, text_24, FontSize, font, color_196);
      }
      name_8 = "ShowOrders_a3a";
      if (ObjectCreate(name_8, OBJ_LABEL, li_88, 0, 0)) {
         ObjectSet(name_8, OBJPROP_XDISTANCE, 412);
         ObjectSet(name_8, OBJPROP_YDISTANCE, y_84);
         ObjectSetText(name_8, "MarginMode " + DoubleToStr(AccountFreeMarginMode(), 0), FontSize, font, color_196);
      }
      y_84 += FontSize + 0.7 * FontSize;
      text_24 = "Margin In Use Alert " + "1 @ " + DoubleToStr(MA1, 0) + "%, " + "2 @ " + DoubleToStr(MA2, 0) + "%, " + "3 @ " + DoubleToStr(MA3, 0) + "%";
      name_8 = "ShowOrders_a4";
      if (ObjectCreate(name_8, OBJ_LABEL, li_88, 0, 0)) {
         ObjectSet(name_8, OBJPROP_XDISTANCE, 12);
         ObjectSet(name_8, OBJPROP_YDISTANCE, y_84);
         ObjectSetText(name_8, text_24, FontSize, font, DeepPink);
      }
      name_8 = "ShowOrders_a4a";
      if (ObjectCreate(name_8, OBJ_LABEL, li_88, 0, 0)) {
         ObjectSet(name_8, OBJPROP_XDISTANCE, 412);
         ObjectSet(name_8, OBJPROP_YDISTANCE, y_84);
         ObjectSetText(name_8, "$" + DoubleToStr(Deposits - Bonuses, 0) + ", ROI " + DoubleToStr(100.0 * ((AccountBalance() - Deposits) / (Deposits - Bonuses)), 1) + "%",
            FontSize, font, color_196);
      }
      ObjectsRedraw();
   }
   return (0);
}
