//|-----------------------------------------------------------------------------------------|
//|                                                    WallStreetForexRobot_v3.9_Sqlite.mq4 |
//|                                                            Copyright © 2012, Dennis Lee |
//| Assert History                                                                          |
//| 1.3.2   Added function GetAccountOrdersTotal() to ensure total trades do not exceed.    |
//| 1.3.1   Check if MagicNumber is returned correctly by broker. If not then set           |
//|            MaxAccountTrades=0 (disable the EA).                                         |
//| 1.3.0   Added PlusTD to replace previous support functions for TDSetup indicator.       |
//| 1.2.0   Added qualifier ONE (1), checks that TDST UpLine has been broken, and DnLine    |
//|            has NOT been broken, before opening a LONG trade. Conversely, checks that    |
//|            TDST DnLine has been broken and UpLine has NOT been broken, before opening   |
//|            a SHORT trade. This reduces the likelihood that the market retracement       |
//|            turns to a major reversal trend.                                             |
//| 1.12    Fixed memory leak in OrderSelect() for SELECT_BY_TICKET mode.                   |
//| 1.11    Added dynamic arrays to process OrderSelect.                                    |
//| 1.10    Added PlusTurtle.mqh and PlusGhost.mqh v1.62 (SqLite v1.11).                    |
//| 1.00    Generated by EX4 TO MQ4 decompile Service.                                      |
//|-----------------------------------------------------------------------------------------|
#property copyright "Copyright © 2012, Dennis Lee"
#property link      ""

#import "wininet.dll"
   int InternetOpenA(string a0, int a1, string a2, string a3, int a4);
   int InternetOpenUrlA(int a0, string a1, string a2, int a3, int a4, int a5);
   int InternetCloseHandle(int a0);
#import "WALLSTREET.dll"
   int SessionInit(int a0, int a1, int a2, int a3, string a4);
   int SessionDeinit(int a0, int a1, int a2, int a3, string a4);
   int ParamValue(int a0, int a1);
   bool CheckCloseLong(int a0, double a1, double a2, double a3, double a4, double a5, double a6, double a7, double a8, double a9);
   bool CheckCloseShort(int a0, double a1, double a2, double a3, double a4, double a5, double a6, double a7, double a8, double a9);
   bool CheckOpenLong(int a0, double a1, double a2, double a3, double a4, double a5, double a6, double a7, double a8);
   bool CheckOpenShort(int a0, double a1, double a2, double a3, double a4, double a5, double a6, double a7, double a8);
#import

//--- Assert 2: Plus include files
extern string     s1                         = "-->PlusTD Settings<--";
#include <PlusTD.mqh>
extern string     s2                         = "-->PlusTurtle Settings<--";
#include <PlusTurtle.mqh>
extern string     s3                         = "-->PlusGhost Settings<--";
#include <PlusGhost.mqh>

//|-----------------------------------------------------------------------------------------|
//|                           E X T E R N A L   V A R I A B L E S                           |
//|-----------------------------------------------------------------------------------------|
extern string     e1                         = "Debug Properties";
extern bool       EaViewDebugNotify          = false;
extern int        EaViewDebug                = 0;
extern int        EaViewDebugNoStack         = 1000;
extern int        EaViewDebugNoStackEnd      = 10;
string EaName = "WallStreetForexRobot_v3.9_Sqlite";
string EaVer = "1.3.2";
extern int Magic = 4698523;
extern string EA_Comment = "";
extern int MaxSpread = 4;
extern int Slippage = 2;
int gi_96 = 3;
int gi_100 = 3;
extern bool StealthMode = FALSE;
bool gi_108 = TRUE;
extern bool CloseOnlyOnProfit = FALSE;
extern bool NFA = FALSE;
extern bool No_Hedge = FALSE;
extern string CS = "==== Custom Settings ====";
extern int StopLoss = 0;
extern int TakeProfit = 0;
extern int SecureProfit = 0;
extern int SecureProfitTriger = 0;
extern bool UseCustomPair = FALSE;
extern string UseSettingsFrom = "EURUSD";
extern string MM = "==== Risk Management ====";
extern bool RecoveryMode = FALSE;
extern double FixedLots = 0.1;
extern double AutoMM = 0.0;
extern double AutoMM_Max = 20.0;
extern int MaxAccountTrades = 3;
extern string FE = "==== Friday Exit Rules ====";
extern bool FridayExit = FALSE;
extern int LastTradeHour = 19;
extern int ExitHour = 20;
//|-----------------------------------------------------------------------------------------|
//|                           I N T E R N A L   V A R I A B L E S                           |
//|-----------------------------------------------------------------------------------------|
int gi_220 = 50;
double gd_224 = 25.0;
double gd_232 = 1.1;
int g_period_240 = 0;
int gi_244 = 0;
int gi_248 = 0;
int gi_252 = 0;
int gi_256 = 0;
int gi_260 = 0;
int gi_264 = 0;
int g_period_268 = 0;
int gi_272 = 0;
int gi_276 = 0;
int gi_280 = 0;
int gi_284 = 0;
int gi_288 = 0;
int g_period_292 = 0;
int gi_296 = 0;
int g_period_300 = 0;
int gi_304 = 0;
int gi_308 = 0;
int gi_312 = -1;
string gs_316 = "";
bool gi_324 = TRUE;
bool gi_328 = FALSE;
int g_stoplevel_332 = 0;
double g_minlot_336 = 0.01;
double g_maxlot_344 = 0.01;
double g_lotstep_352 = 0.01;
int g_lotsize_360 = 100000;
double g_marginrequired_364 = 1000.0;
double gd_372 = 0.0001;
double gd_unused_380 = 0.1;
double gd_unused_388 = 1.0;

//|-----------------------------------------------------------------------------------------|
//|                             I N I T I A L I Z A T I O N                                 |
//|-----------------------------------------------------------------------------------------|
int CheckWWW() {
   int li_20;
   bool li_ret_0 = TRUE;
   string ls_4 = "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; Q312461)";
   bool li_12 = FALSE;
   int li_16 = InternetOpenA(ls_4, li_12, "0", "0", 0);
   if (li_16 != 0) {
      li_20 = InternetOpenUrlA(li_16, "http://www.wallstreet-forex.com", "0", 0, -2080374528, 0);
      if (li_20 == 0) li_ret_0 = FALSE;
      else InternetCloseHandle(li_20);
      InternetCloseHandle(li_16);
   } else li_ret_0 = FALSE;
   return (li_ret_0);
}

void init() {
   gi_324 = TRUE;
   gi_312 = -1;
   Comment("");
   if (ObjectFind("BKGR") >= 0) ObjectDelete("BKGR");
   if (ObjectFind("BKGR2") >= 0) ObjectDelete("BKGR2");
   if (ObjectFind("BKGR3") >= 0) ObjectDelete("BKGR3");
   if (ObjectFind("BKGR4") >= 0) ObjectDelete("BKGR4");
   if (ObjectFind("LV") >= 0) ObjectDelete("LV");
//--- Assert 2: Init Plus   
   TDInit();
   TurtleInit();
   GhostInit();
}

//|-----------------------------------------------------------------------------------------|
//|                             D E I N I T I A L I Z A T I O N                             |
//|-----------------------------------------------------------------------------------------|
int deinit() {
//--- Assert 1: DeInit Plus
   GhostDeInit();
   Comment("");
   if (ObjectFind("BKGR") >= 0) ObjectDelete("BKGR");
   if (ObjectFind("BKGR2") >= 0) ObjectDelete("BKGR2");
   if (ObjectFind("BKGR3") >= 0) ObjectDelete("BKGR3");
   if (ObjectFind("BKGR4") >= 0) ObjectDelete("BKGR4");
   if (ObjectFind("LV") >= 0) ObjectDelete("LV");
   if (gi_312 != -1) gi_312 = MyDeinit();
   return (0);
}

//|-----------------------------------------------------------------------------------------|
//|                               M A I N   P R O C E D U R E                               |
//|-----------------------------------------------------------------------------------------|
int start() {
   double price_8;
   double ld_16;
   double ld_24;
   color color_32;
   double lots_40;
   int ticket_144;
   double price_156;
   double price_164;
   string ls_180;
   string ls_0 = "";
   double ld_48 = 0;
   double ld_56 = 0;
   double ld_64 = 0;
   double ld_72 = 1;
   if (DayOfWeek() == 1 && iVolume(NULL, PERIOD_D1, 0) < 5.0) return (0);
   if (StringLen(Symbol()) < 6) return (0);
   if (gi_324) {
      Comment("\nInitializing ...");
      Sleep(1000);
      RefreshRates();
      gi_324 = FALSE;
      g_stoplevel_332 = MarketInfo(Symbol(), MODE_STOPLEVEL);
      g_minlot_336 = MarketInfo(Symbol(), MODE_MINLOT);
      g_maxlot_344 = MarketInfo(Symbol(), MODE_MAXLOT);
      g_lotsize_360 = MarketInfo(Symbol(), MODE_LOTSIZE);
      g_lotstep_352 = MarketInfo(Symbol(), MODE_LOTSTEP);
      g_marginrequired_364 = MarketInfo(Symbol(), MODE_MARGINREQUIRED);
      if (Digits <= 3) gd_372 = 0.01;
      else gd_372 = 0.0001;
      if (Digits == 3 || Digits == 5) gd_unused_380 = 0.1;
      else gd_unused_380 = 1;
      Sleep(1000);
      gi_328 = CheckWWW();
      Sleep(1000);
      if (!gi_328) gi_324 = TRUE;
   }
   if ((!IsTesting()) && IsStopped()) return (0);
   if ((!IsTesting()) && !IsTradeAllowed()) return (0);
   if ((!IsTesting()) && IsTradeContextBusy()) return (0);
   if (IsDllsAllowed() == FALSE) {
      Comment("\nWarning: Set Parameter **AllowDLL Imports** ON in menu Tools -> Options -> ExpertAdvisors.");
      Print("Warning: Set Parameter **AllowDLL Imports** ON in menu Tools -> Options -> ExpertAdvisors.");
      Alert("Warning: Set Parameter **AllowDLL Imports** ON in menu Tools -> Options -> ExpertAdvisors.");
      Sleep(30000);
      return (0);
   }
   if (gi_312 <= 0) {
      if (!gi_328) {
         Comment("\nInternet connection problem");
         Alert("Internet connection problem");
         Sleep(10000);
         return (0);
      }
      Comment("\nUpdating settings ...");
      Sleep(2000);
      gi_312 = MyFirstInit();
      Sleep(2000);
      if (gi_312 < 0) Comment("\nInitializing ...");
   }
   if (gi_312 <= 0) {
      if (gi_312 == -8) {
         Comment("\nUnsupported currency pair " + gs_316 + ", Bid: " + DoubleToStr(Bid, Digits) + ", Ask: " + DoubleToStr(Ask, Digits));
         Alert("Unsupported currency pair " + gs_316 + ", Bid: " + DoubleToStr(Bid, Digits) + ", Ask: " + DoubleToStr(Ask, Digits));
      } else {
         Comment("\nInitialization is failed with error code " + DoubleToStr(gi_312, 0));
         Alert("Initialization is failed with error code " + DoubleToStr(gi_312, 0));
      }
      Sleep(10000);
      return (0);
   }
   if (g_period_240 <= 0 || g_period_268 <= 0 || g_period_292 <= 0 || g_period_300 <= 0) {
      Comment("\nWrong initialization parameters for pair " + Symbol());
      Alert("Wrong initialization parameters for pair " + Symbol());
      Sleep(10000);
      return (0);
   }
//--- Assert 1: Refresh Plus   
   GhostRefresh();
   HideTestIndicators(TRUE);
   double iclose_80 = iClose(NULL, PERIOD_M15, 1);
   double ima_88 = iMA(NULL, PERIOD_M15, g_period_240, 0, MODE_SMMA, PRICE_CLOSE, 1);
   double iwpr_96 = iWPR(NULL, PERIOD_M15, g_period_268, 1);
   double iatr_104 = iATR(NULL, PERIOD_M15, g_period_292, 1);
   double icci_112 = iCCI(NULL, PERIOD_M15, g_period_300, PRICE_TYPICAL, 1);
   HideTestIndicators(FALSE);
   double ld_120 = 0;
   if (StringSubstr(AccountCurrency(), 0, 3) == "JPY") {
      ld_120 = MarketInfo("USDJPY" + StringSubstr(Symbol(), 6), MODE_BID);
      if (ld_120 > 0.1) ld_72 = ld_120;
      else ld_72 = 84;
   }
   if (StringSubstr(AccountCurrency(), 0, 3) == "GBP") {
      ld_120 = MarketInfo("GBPUSD" + StringSubstr(Symbol(), 6), MODE_BID);
      if (ld_120 > 0.1) ld_72 = 1 / ld_120;
      else ld_72 = 0.6211180124;
   }
   if (StringSubstr(AccountCurrency(), 0, 3) == "EUR") {
      ld_120 = MarketInfo("EURUSD" + StringSubstr(Symbol(), 6), MODE_BID);
      if (ld_120 > 0.1) ld_72 = 1 / ld_120;
      else ld_72 = 0.7042253521;
   }
   if (AutoMM > 0.0 && (!RecoveryMode)) lots_40 = MathMax(g_minlot_336, MathMin(g_maxlot_344, MathCeil(MathMin(AutoMM_Max, AutoMM) / ld_72 / 100.0 * AccountFreeMargin() / g_lotstep_352 / (g_lotsize_360 / 100)) * g_lotstep_352));
   if (AutoMM > 0.0 && RecoveryMode) lots_40 = CalcLots();
   if (AutoMM == 0.0) lots_40 = FixedLots;
   ls_0 = ls_0 
      + "\n  " 
      + "\n " 
      + "\n  Authorization - OK!" 
      + "\n -----------------------------------------------" 
      + "\n  SL = " + StopLoss + " pips / TP = " + TakeProfit + " pips" 
   + "\n  Spread = " + DoubleToStr((Ask - Bid) / gd_372, 1) + " pips";
   if (Ask - Bid > MaxSpread * gd_372) ls_0 = ls_0 + " - TOO HIGH";
   else ls_0 = ls_0 + " - NORMAL";
   ls_0 = ls_0 
   + "\n -----------------------------------------------";
   if (AutoMM > 0.0) {
      ls_0 = ls_0 
         + "\n  AutoMM - ENABLED" 
      + "\n  Risk = " + DoubleToStr(AutoMM, 1) + "%";
   }
   ls_0 = ls_0 
   + "\n  Trading Lots = " + DoubleToStr(lots_40, 2);
   ls_0 = ls_0 
   + "\n -----------------------------------------------";
   if (RecoveryMode) {
      ls_0 = ls_0 
      + "\n  Recovery Mode - ENABLED";
   } else {
      ls_0 = ls_0 
      + "\n  Recovery Mode - DISABLED";
   }
   if (StealthMode) {
      ls_0 = ls_0 
      + "\n  Stealth Mode - ENABLED";
   } else {
      ls_0 = ls_0 
      + "\n  Stealth Mode - DISABLED";
   }
   ls_0 = ls_0 
   + "\n -----------------------------------------------";
//--- Assert 1: Replace comment with Ghost comment   
   Comment(GhostComment(TurtleComment(TDComment(ls_0+"\n"))));
   if (ObjectFind("BKGR") < 0) {
      ObjectCreate("BKGR", OBJ_LABEL, 0, 0, 0);
      ObjectSetText("BKGR", "g", 110, "Webdings", LightSlateGray);
      ObjectSet("BKGR", OBJPROP_CORNER, 0);
      ObjectSet("BKGR", OBJPROP_BACK, TRUE);
      ObjectSet("BKGR", OBJPROP_XDISTANCE, 5);
      ObjectSet("BKGR", OBJPROP_YDISTANCE, 15);
   }
   if (ObjectFind("BKGR2") < 0) {
      ObjectCreate("BKGR2", OBJ_LABEL, 0, 0, 0);
      ObjectSetText("BKGR2", "g", 110, "Webdings", DimGray);
      ObjectSet("BKGR2", OBJPROP_BACK, TRUE);
      ObjectSet("BKGR2", OBJPROP_XDISTANCE, 5);
      ObjectSet("BKGR2", OBJPROP_YDISTANCE, 60);
   }
   if (ObjectFind("BKGR3") < 0) {
      ObjectCreate("BKGR3", OBJ_LABEL, 0, 0, 0);
      ObjectSetText("BKGR3", "g", 110, "Webdings", DimGray);
      ObjectSet("BKGR3", OBJPROP_CORNER, 0);
      ObjectSet("BKGR3", OBJPROP_BACK, TRUE);
      ObjectSet("BKGR3", OBJPROP_XDISTANCE, 5);
      ObjectSet("BKGR3", OBJPROP_YDISTANCE, 45);
   }
   if (ObjectFind("LV") < 0) {
      ObjectCreate("LV", OBJ_LABEL, 0, 0, 0);
      ObjectSetText("LV", "WALL STREET ROBOT", 9, "Tahoma Bold", White);
      ObjectSet("LV", OBJPROP_CORNER, 0);
      ObjectSet("LV", OBJPROP_BACK, FALSE);
      ObjectSet("LV", OBJPROP_XDISTANCE, 13);
      ObjectSet("LV", OBJPROP_YDISTANCE, 23);
   }
   if (ObjectFind("BKGR4") < 0) {
      ObjectCreate("BKGR4", OBJ_LABEL, 0, 0, 0);
      ObjectSetText("BKGR4", "g", 110, "Webdings", DimGray);
      ObjectSet("BKGR4", OBJPROP_CORNER, 0);
      ObjectSet("BKGR4", OBJPROP_BACK, TRUE);
      ObjectSet("BKGR4", OBJPROP_XDISTANCE, 5);
      ObjectSet("BKGR4", OBJPROP_YDISTANCE, 84);
   }
   if (TakeProfit < g_stoplevel_332 * Point / gd_372) TakeProfit = g_stoplevel_332 * Point / gd_372;
   if (StopLoss < g_stoplevel_332 * Point / gd_372) StopLoss = g_stoplevel_332 * Point / gd_372;
   Slippage = Slippage * gd_372;
   int count_128 = 0;
   int count_132 = 0;
   int count_136 = 0;
   int count_140 = 0;
   if (CloseOnlyOnProfit) gi_264 = FALSE;
//--- Assert 8: Declare variables
   int      aCommand[];    // 1-OrderModify BUY; 2-OrderClose BUY; 3-OrderModify SELL; 4-OrderClose SELL;
   int      aTicket[];
   double   aLots[];
   double   aOpenPrice[];
   double   aStopLoss[];
   double   aTakeProfit[];
   bool     aOk;
   int      aCount;
//--- Assert 6: Dynamically resize arrays
   ArrayResize(aCommand,MaxAccountTrades);
   ArrayResize(aTicket,MaxAccountTrades);
   ArrayResize(aLots,MaxAccountTrades);
   ArrayResize(aOpenPrice,MaxAccountTrades);
   ArrayResize(aStopLoss,MaxAccountTrades);
   ArrayResize(aTakeProfit,MaxAccountTrades);
//--- Assert 2: Init OrderSelect #1
   int      aTotal = GhostOrdersTotal();
   GhostInitSelect(false,0,SELECT_BY_POS,MODE_TRADES);
   for (int pos_152 = aTotal - 1; pos_152 >= 0; pos_152--) {
      if (!GhostOrderSelect(pos_152, SELECT_BY_POS, MODE_TRADES)) Print("Error in OrderSelect! Position:", pos_152);
      else {
      //--- Assert 6: Populate arrays
         aCommand[aCount]     =  0;
         aTicket[aCount]      =  GhostOrderTicket();
         aLots[aCount]        =  GhostOrderLots();
         aOpenPrice[aCount]   =  GhostOrderOpenPrice();
         aStopLoss[aCount]    =  GhostOrderStopLoss();
         aTakeProfit[aCount]  =  GhostOrderTakeProfit();
         if (GhostOrderType() <= OP_SELL && GhostOrderSymbol() == Symbol()) {
            if (GhostOrderMagicNumber() != Magic) {
               if (GhostOrderType() == OP_BUY) count_136++;
               else count_140++;
            }
            if (GhostOrderMagicNumber() == Magic) {
               ld_64 += GhostOrderProfit();
               if (GhostOrderType() == OP_BUY) ld_48 = (Bid - GhostOrderOpenPrice()) / gd_372;
               else ld_48 = (GhostOrderOpenPrice() - Ask) / gd_372;
               ld_56 += ld_48;
               if (GhostOrderType() == OP_BUY) {
                  count_128++;
                  if (GhostOrderStopLoss() == 0.0 && StealthMode == FALSE) {
                     price_156 = NormalizeDouble(GhostOrderOpenPrice() - StopLoss * gd_372, Digits);
                     price_164 = NormalizeDouble(GhostOrderOpenPrice() + TakeProfit * gd_372, Digits);
                  //--- 5: Assert replace OrderModify a buy trade with arrays
                     aCommand[aCount]     = 1; 
                     aStopLoss[aCount]    = price_156;
                     aTakeProfit[aCount]  = price_164;
                     aCount ++;
                     if( aCount >= MaxAccountTrades ) break;
                     /*GhostOrderModify(GhostOrderTicket(), GhostOrderOpenPrice(), price_156, price_164, 0, Green);*/
                     continue;
                  }
                  if (Bid >= GhostOrderOpenPrice() + TakeProfit * gd_372 || 
                      Bid <= GhostOrderOpenPrice() - StopLoss * gd_372 ||
                     (CloseLong(GhostOrderOpenPrice(), iwpr_96, iclose_80, iOpen(NULL, PERIOD_M1, 1), iClose(NULL, PERIOD_M1, 1)) && 
                      TimeCurrent() - GhostOrderOpenTime() > 180) || 
                     (FridayExit && DayOfWeek() == 5 && Hour() >= ExitHour && 
                      TimeCurrent() - GhostOrderOpenTime() > 180)) {
                     for (int li_148 = 1; li_148 <= MathMax(1, gi_96); li_148++) {
                        RefreshRates();
                     //--- 3: Assert replace OrderClose a buy trade with arrays
                        aCommand[aCount]  = 2;  // OrderClose a buy trade
                        aCount ++;
                        count_128--;
                        if( aCount >= MaxAccountTrades ) break;
                        /*if (GhostOrderClose(GhostOrderTicket(), GhostOrderLots(), NormalizeDouble(Bid, Digits), Slippage, Violet)) { */
                        break;
                        /*}*/
                        Sleep(MathMax(100, 1000 * gi_100));
                     }
                     Sleep(5000);
                     continue;
                  }
                  if (!(Bid - GhostOrderOpenPrice() > SecureProfitTriger * gd_372 && MathAbs(GhostOrderOpenPrice() + SecureProfit * gd_372 - GhostOrderStopLoss()) >= Point)) continue;
               //--- Assert 4: Replace OrderModify a buy trade with arrays.
                  aCommand[aCount]  = 1;
                  aStopLoss[aCount] = NormalizeDouble(GhostOrderOpenPrice() + SecureProfit * gd_372, Digits);
                  aCount ++;
                  if( aCount >= MaxAccountTrades ) break;
                  //GhostOrderModify(GhostOrderTicket(), GhostOrderOpenPrice(), NormalizeDouble(GhostOrderOpenPrice() + SecureProfit * gd_372, Digits), GhostOrderTakeProfit(), 0, Blue);
                  continue;
               } else {
                  count_132++;
                  if (GhostOrderStopLoss() == 0.0 && StealthMode == FALSE) {
                     price_156 = NormalizeDouble(GhostOrderOpenPrice() + StopLoss * gd_372, Digits);
                     price_164 = NormalizeDouble(GhostOrderOpenPrice() - TakeProfit * gd_372, Digits);
                  //--- Assert 5: Replace OrderModify a sell trade with arrays.
                     aCommand[aCount]     = 3;
                     aStopLoss[aCount]    = price_156;
                     aTakeProfit[aCount]  = price_164;
                     aCount ++;
                     if( aCount >= MaxAccountTrades ) break;
                     //GhostOrderModify(GhostOrderTicket(), GhostOrderOpenPrice(), price_156, price_164, 0, Green);
                     continue;
                  }
                  if (Ask <= GhostOrderOpenPrice() - TakeProfit * gd_372 || 
                     Ask >= GhostOrderOpenPrice() + StopLoss * gd_372 || 
                     (CloseShort(GhostOrderOpenPrice(), iwpr_96, iclose_80, iOpen(NULL, PERIOD_M1, 1), iClose(NULL, PERIOD_M1, 1)) && 
                     TimeCurrent() - GhostOrderOpenTime() > 180) || 
                     (FridayExit && DayOfWeek() == 5 && Hour() >= ExitHour && 
                     TimeCurrent() - GhostOrderOpenTime() > 180)) {
                     for (li_148 = 1; li_148 <= MathMax(1, gi_96); li_148++) {
                        RefreshRates();
                     //--- Assert 3: Replace OrderClose a sell trade with arrays.
                        aCommand[aCount]  = 4;
                        aCount ++;
                        count_132--;
                        if( aCount >= MaxAccountTrades ) break;
                        /*if (GhostOrderClose(GhostOrderTicket(), GhostOrderLots(), NormalizeDouble(Ask, Digits), Slippage, Violet)) {*/
                        break;
                        /*}*/
                        Sleep(MathMax(100, 1000 * gi_100));
                     }
                     Sleep(5000);
                     continue;
                  }
                  if (GhostOrderOpenPrice() - Ask > SecureProfitTriger * gd_372 && MathAbs(GhostOrderOpenPrice() - SecureProfit * gd_372 - GhostOrderStopLoss()) >= Point) 
                  {
                  //--- Assert 4: Replace OrderModify a sell trade with arrays.
                     aCommand[aCount]     = 3;
                     aStopLoss[aCount]    = NormalizeDouble(GhostOrderOpenPrice() - SecureProfit * gd_372, Digits);
                     aCount ++;
                     if( aCount >= MaxAccountTrades ) break;
                     //GhostOrderModify(GhostOrderTicket(), GhostOrderOpenPrice(), NormalizeDouble(GhostOrderOpenPrice() - SecureProfit * gd_372, Digits), GhostOrderTakeProfit(), 0, Red);
                  }
               }
            }
         }
      }
   }
//--- Assert 1: Free OrderSelect #1   
   GhostFreeSelect(true);
//--- Assert for: process array of commands
   for(int i=0; i<aCount; i++)
   {
      switch( aCommand[i] )
      {
         case 1:  // OrderModify Buy
            GhostOrderModify( aTicket[i], aOpenPrice[i], aStopLoss[i], aTakeProfit[i], 0, Blue );
            break;
         case 2:  // OrderClose Buy
            GhostOrderClose( aTicket[i], aLots[i], NormalizeDouble(Bid, Digits), Slippage, Violet );
            break;
         case 3:  // OrderModify Sell
            GhostOrderModify( aTicket[i], aOpenPrice[i], aStopLoss[i], aTakeProfit[i], 0, Red );
            break;
         case 4:  // OrderClose Sell
            GhostOrderClose( aTicket[i], aLots[i], NormalizeDouble(Ask, Digits), Slippage, Violet );
            break;
      }
   }
   ls_0 = ls_0 
   + "\n  Account Balance = " + DoubleToStr(AccountBalance(), 2);
   if (count_128 == 0 && count_132 == 0) {
      ls_0 = ls_0 
         + "\n  No active trades" 
      + "\n";
   } else {
      ls_0 = ls_0 
         + "\n  Current trade " + DoubleToStr(ld_56, 1) 
      + "\n  Account Profit = " + DoubleToStr(ld_64, 2);
   }
//--- Assert 1: Replace comment with Ghost comment   
   Comment(GhostComment(TurtleComment(TDComment(ls_0+"\n"))));
   bool li_172 = TRUE;
   bool li_176 = TRUE;
   if (NFA == TRUE && count_132 > 0 || count_128 > 0) {
      li_172 = FALSE;
      li_176 = FALSE;
   }
   if (NFA == TRUE && count_140 > 0 || count_136 > 0) {
      li_172 = FALSE;
      li_176 = FALSE;
   }
   if (No_Hedge == TRUE && count_132 > 0 || count_140 > 0) li_172 = FALSE;
   if (No_Hedge == TRUE && count_128 > 0 || count_136 > 0) li_176 = FALSE;
   if (!gi_108) gi_296 = 1000;
   else gi_296 = gi_296;
   if (iatr_104 <= gi_288 * gd_372) return (0);
   if (GhostOrdersTotal() >= MaxAccountTrades) return (0);
   if (FridayExit && DayOfWeek() == 5 && Hour() > LastTradeHour) return (0);
   int cmd_36 = -1;
   if (count_128 < 1 && OpenLong(iclose_80, ima_88, iwpr_96, icci_112)) {
      if (Ask - Bid > MaxSpread * gd_372) {
         Print("BUY not taken!!! - High spread...");
         Sleep(1000);
      } else {
         if (!li_172) {
            Print("BUY not taken!!! - No Hedge, or FIFO restriction ...");
            Sleep(1000);
         } else {
            ls_180 = "BUY";
            cmd_36 = 0;
            color_32 = Aqua;
            RefreshRates();
            price_8 = NormalizeDouble(Ask, Digits);
            ld_16 = price_8 - StopLoss * gd_372;
            ld_24 = price_8 + TakeProfit * gd_372;
         }
      }
   }
   if (count_132 < 1 && OpenShort(iclose_80, ima_88, iwpr_96, icci_112)) {
      if (Ask - Bid > MaxSpread * gd_372) {
         Print("SELL not taken!!! - High spead...");
         Sleep(1000);
      } else {
         if (!li_176) {
            Print("SELL not taken!!! - No Hedge, or FIFO restriction ...");
            Sleep(1000);
         } else {
            ls_180 = "SELL";
            cmd_36 = 1;
            color_32 = Red;
            RefreshRates();
            price_8 = NormalizeDouble(Bid, Digits);
            ld_16 = price_8 + StopLoss * gd_372;
            ld_24 = price_8 - TakeProfit * gd_372;
         }
      }
   }
   if (cmd_36 >= OP_BUY && CheckLossPause()) {
      bool  isWave1Ok = true;
      int   numTrades = 0;
      for (li_148 = 1; li_148 <= MathMax(1, gi_96); li_148++) {
         if( cmd_36 == OP_BUY )
         {
            isWave1Ok = TDWave1Buy();
            numTrades = count_128;
         }
         if( cmd_36 == OP_SELL )
         {
            isWave1Ok = TDWave1Sell();
            numTrades = count_132;
         }
         if( GetAccountOrdersTotal() < MaxAccountTrades )
         {
            if( isWave1Ok ) ticket_144 = GhostOrderSend(Symbol(), cmd_36, lots_40, price_8, Slippage, 0, 0, EA_Comment, Magic, 0, color_32);
         }
         if (ticket_144 > 0)
         {
            EaDebugPrint( 0, "start",
               EaDebugStr("EaName", EaName)+
               EaDebugStr("EaVer", EaVer)+
               EaDebugStr("sym", Symbol())+
               EaDebugInt("mgc", Magic)+
               EaDebugInt("ticket", ticket_144)+
               EaDebugInt("type", cmd_36)+
               EaDebugDbl("lot", lots_40)+
               EaDebugDbl("openPrice", price_8)+
               EaDebugInt("numTrades", numTrades)+
               TDDebugGlobal()+
               EaDebugBln("TDWave1", true) );
            break;
         }
         Sleep(MathMax(100, 1000 * gi_100));
         RefreshRates();
         if (cmd_36 == OP_BUY) price_8 = NormalizeDouble(Ask, Digits);
         else
            if (cmd_36 == OP_SELL) price_8 = NormalizeDouble(Bid, Digits);
      }
      Sleep(5000);
      if (ticket_144 > 0) {
      //--- Assert 1: Init OrderSelect #2
         GhostInitSelect(true,ticket_144,SELECT_BY_TICKET,MODE_TRADES);
         if( GhostOrderSelect(ticket_144, SELECT_BY_TICKET, MODE_TRADES) ) 
         {
            Print("Order " + ls_180 + " opened!: ", GhostOrderOpenPrice());
         //--- Check if Magic is set correctly by broker
            if( GhostOrderMagicNumber() != Magic )
            {
               EaDebugPrint( 0, "start",
                  EaDebugStr("EaName", EaName)+
                  EaDebugStr("EaVer", EaVer)+
                  EaDebugStr("sym", Symbol())+
                  EaDebugInt("mgc", Magic)+
                  EaDebugInt("ticket", ticket_144)+
                  EaDebugInt("type", cmd_36)+
                  EaDebugDbl("lot", lots_40)+
                  EaDebugDbl("openPrice", price_8)+
                  " Magic number not returned by broker. Set MaxAccountTrades=0." );
               MaxAccountTrades=0;
            }
         }
      //--- Assert 1: Free OrderSelect #2
         GhostFreeSelect(false);
      } else Print("Error opening " + ls_180 + " order!: ", GetLastError());
   }
   return (0);
}

double CalcLots() {
   double ld_16;
   int count_24;
   double ld_28;
   int li_36;
   double ld_40;
   int li_48;
   double ld_52;
   int li_60;
   double ld_8 = 1;
   if (gd_232 > 0.0 && AutoMM > 0.0) {
      ld_16 = 0;
      count_24 = 0;
      ld_28 = 0;
      li_36 = 0;
      ld_40 = 0;
      li_48 = 0;
   //--- Assert 2: Init OrderSelect #3
      int total = GhostOrdersHistoryTotal();
      GhostInitSelect(false,0,SELECT_BY_POS,MODE_HISTORY);
      for (int pos_64 = total - 1; pos_64 >= 0; pos_64--) {
         if (GhostOrderSelect(pos_64, SELECT_BY_POS, MODE_HISTORY)) {
            if (GhostOrderSymbol() == Symbol() && GhostOrderMagicNumber() == Magic) {
               count_24++;
               ld_16 += GhostOrderProfit();
               if (ld_16 > ld_40) {
                  ld_40 = ld_16;
                  li_48 = count_24;
               }
               if (ld_16 < ld_28) {
                  ld_28 = ld_16;
                  li_36 = count_24;
               }
               if (count_24 >= gi_220) break;
            }
         }
      }
   //--- Assert 1: Free OrderSelect #3
      GhostFreeSelect(false);
      if (li_48 <= li_36) ld_8 = MathPow(gd_232, li_36);
      else {
         ld_16 = ld_40;
         count_24 = li_48;
         ld_52 = ld_40;
         li_60 = li_48;
      //--- Assert 1: Init OrderSelect #4
         GhostInitSelect(false,0,SELECT_BY_POS,MODE_HISTORY);
         for (pos_64 = GhostOrdersHistoryTotal() - li_48 - 1; pos_64 >= 0; pos_64--) {
            if (GhostOrderSelect(pos_64, SELECT_BY_POS, MODE_HISTORY)) {
               if (GhostOrderSymbol() == Symbol() && GhostOrderMagicNumber() == Magic) {
                  if (count_24 >= gi_220) break;
                  count_24++;
                  ld_16 += GhostOrderProfit();
                  if (ld_16 < ld_52) {
                     ld_52 = ld_16;
                     li_60 = count_24;
                  }
               }
            }
         }
      //--- Assert 2: Free OrderSelect #4
         GhostFreeSelect(false);
         if (li_60 == li_48 || ld_52 == ld_40) ld_8 = MathPow(gd_232, li_36);
         else {
            if (MathAbs(ld_28 - ld_40) / MathAbs(ld_52 - ld_40) >= (gd_224 + 100.0) / 100.0) ld_8 = MathPow(gd_232, li_36);
            else ld_8 = MathPow(gd_232, li_60);
         }
      }
   }
   for (double ld_ret_0 = MathMax(g_minlot_336, MathMin(g_maxlot_344, MathCeil(MathMin(AutoMM_Max, ld_8 * AutoMM) / 100.0 * AccountFreeMargin() / g_lotstep_352 / (g_lotsize_360 / 100)) * g_lotstep_352)); ld_ret_0 >= 2.0 * g_minlot_336 &&
      1.05 * (ld_ret_0 * g_marginrequired_364) >= AccountFreeMargin(); ld_ret_0 -= g_minlot_336) {
   }
   return (ld_ret_0);
}

int CheckLossPause() {
   int datetime_4;
   bool li_ret_0 = TRUE;
   if (gi_304 > 0 && gi_308 > 0) {
      datetime_4 = 0;
   //--- Assert 2: Init OrderSelect #5
      int total = GhostOrdersHistoryTotal();
      GhostInitSelect(false,0,SELECT_BY_POS,MODE_HISTORY);
      for (int pos_8 = total - 1; pos_8 >= 0; pos_8--) {
         if (GhostOrderSelect(pos_8, SELECT_BY_POS, MODE_HISTORY)) {
            if (GhostOrderSymbol() == Symbol() && GhostOrderMagicNumber() == Magic) {
               if (!((GhostOrderType() == OP_BUY && (GhostOrderClosePrice() - GhostOrderOpenPrice()) / gd_372 <= (-gi_304)) || (GhostOrderType() == OP_SELL && (GhostOrderOpenPrice() - GhostOrderClosePrice()) / gd_372 <= (-gi_304)))) break;
               datetime_4 = GhostOrderCloseTime();
               break;
            }
         }
      }
   //--- Assert 1: Free OrderSelect #5
      GhostFreeSelect(false);
      if (TimeCurrent() - datetime_4 < 3600 * gi_308) li_ret_0 = FALSE;
   }
   return (li_ret_0);
}

double GetAccountOrdersTotal() 
{
   int ret;
//--- Assert 2: Init OrderSelect #13
   int total = GhostOrdersTotal();
   GhostInitSelect(true,0,SELECT_BY_POS,MODE_TRADES);
   for( int pos = 0; pos <= total - 1; pos++ ) 
   {
      if( GhostOrderSelect(pos, SELECT_BY_POS, MODE_TRADES) )
      {
      //--- Count ALL trades in account
      //       For ALL symbols
      //       For ALL magic / non-magic numbers
      //       For ALL opened trades
      //       Exclude pending orders
      //       Exclude historical orders
         if (GhostOrderType() <= OP_SELL) ret ++;
      }
   }
//--- Assert 1: Free OrderSelect #13
   GhostFreeSelect(false);
   return (ret);
}

int MyFirstInit() {
   if (UseCustomPair) gs_316 = StringSubstr(UseSettingsFrom, 0, 6);
   else gs_316 = StringSubstr(Symbol(), 0, 6);
   int li_ret_0 = SessionInit(AccountNumber(), IsTesting(), IsDemo(), WindowHandle(Symbol(), Period()), gs_316);
   if (li_ret_0 == -8 && StringFind(",EURUSD,GBPUSD,USDCHF,USDJPY,USDCAD,", "," + gs_316 + ",") >= 0) {
      Comment("\nUpdating settings (" + gs_316 + ")...");
      li_ret_0 = SessionDeinit(AccountNumber(), IsTesting(), IsDemo(), WindowHandle(Symbol(), Period()), gs_316);
      Sleep(3000);
      li_ret_0 = SessionInit(AccountNumber(), IsTesting(), IsDemo(), WindowHandle(Symbol(), Period()), gs_316);
   }
   if (li_ret_0 >= 0) {
      g_period_240 = ParamValue(li_ret_0, 1);
      gi_244 = ParamValue(li_ret_0, 2);
      gi_248 = ParamValue(li_ret_0, 3);
      gi_252 = ParamValue(li_ret_0, 4);
      gi_256 = ParamValue(li_ret_0, 5);
      gi_260 = ParamValue(li_ret_0, 6);
      gi_264 = ParamValue(li_ret_0, 7);
      g_period_268 = ParamValue(li_ret_0, 8);
      gi_272 = ParamValue(li_ret_0, 9);
      if (SecureProfit <= 0) SecureProfit = ParamValue(li_ret_0, 10);
      if (SecureProfitTriger <= 0) SecureProfitTriger = ParamValue(li_ret_0, 11);
      gi_276 = ParamValue(li_ret_0, 12);
      gi_280 = ParamValue(li_ret_0, 13);
      gi_284 = ParamValue(li_ret_0, 14);
      gi_288 = ParamValue(li_ret_0, 15);
      g_period_292 = ParamValue(li_ret_0, 16);
      gi_296 = ParamValue(li_ret_0, 17);
      g_period_300 = ParamValue(li_ret_0, 18);
      gi_304 = ParamValue(li_ret_0, 19);
      gi_308 = ParamValue(li_ret_0, 20);
      if (StopLoss <= 0) StopLoss = ParamValue(li_ret_0, 21);
      if (TakeProfit <= 0) TakeProfit = ParamValue(li_ret_0, 22);
   }
   return (li_ret_0);
}

int MyDeinit() {
   int li_ret_0;
   if (UseCustomPair) li_ret_0 = SessionDeinit(AccountNumber(), IsTesting(), IsDemo(), WindowHandle(Symbol(), Period()), StringSubstr(UseSettingsFrom, 0, 6));
   else li_ret_0 = SessionDeinit(AccountNumber(), IsTesting(), IsDemo(), WindowHandle(Symbol(), Period()), StringSubstr(Symbol(), 0, 6));
   return (li_ret_0);
}

int CloseLong(double ad_0, double ad_8, double ad_16, double ad_24, double ad_32) {
   bool li_40 = FALSE;
   li_40 = CheckCloseLong(gi_312, ad_0, ad_8, ad_16, ad_24, ad_32, gi_264, Bid, Ask, gd_372);
   return (li_40);
}

int CloseShort(double ad_0, double ad_8, double ad_16, double ad_24, double ad_32) {
   bool li_40 = FALSE;
   li_40 = CheckCloseShort(gi_312, ad_0, ad_8, ad_16, ad_24, ad_32, gi_264, Bid, Ask, gd_372);
   return (li_40);
}

int OpenLong(double ad_0, double ad_8, double ad_16, double ad_24) {
   bool li_32 = FALSE;
   li_32 = CheckOpenLong(gi_312, ad_0, ad_8, ad_16, ad_24, gi_296, Bid, Ask, gd_372);
   return (li_32);
}

int OpenShort(double ad_0, double ad_8, double ad_16, double ad_24) {
   bool li_32 = FALSE;
   li_32 = CheckOpenShort(gi_312, ad_0, ad_8, ad_16, ad_24, gi_296, Bid, Ask, gd_372);
   return (li_32);
}
//|-----------------------------------------------------------------------------------------|
//|                                     C O M M E N T                                       |
//|-----------------------------------------------------------------------------------------|
void EaDebugPrint(int dbg, string fn, string msg)
{
   static int noStackCount;
   if(EaViewDebug>=dbg)
   {
      if(dbg>=2 && EaViewDebugNoStack>0)
      {
         if( MathMod(noStackCount,EaViewDebugNoStack) <= EaViewDebugNoStackEnd )
            Print(EaViewDebug,"-",noStackCount,":",fn,"(): ",msg);
            
         noStackCount ++;
      }
      else
      {
         if(EaViewDebugNotify)   SendNotification( EaViewDebug + ":" + fn + "(): " + msg );
         Print(EaViewDebug,":",fn,"(): ",msg);
      }
   }
}
string EaDebugInt(string key, int val)
{
   return( StringConcatenate(";",key,"=",val) );
}
string EaDebugDbl(string key, double val, int dgt=5)
{
   return( StringConcatenate(";",key,"=",NormalizeDouble(val,dgt)) );
}
string EaDebugStr(string key, string val)
{
   return( StringConcatenate(";",key,"=\"",val,"\"") );
}
string EaDebugBln(string key, bool val)
{
   string valType;
   if( val )   valType="true";
   else        valType="false";
   return( StringConcatenate(";",key,"=",valType) );
}
//|------------------------------------------------------------------------------------------|
//|                       E N D   O F   E X P E R T   A D V I S O R                          |
//|------------------------------------------------------------------------------------------|
